//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "client")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub name: String,
    pub ip: String,
    pub key: String,
    pub active: bool,
    pub dns: bool,
    pub proxy: bool,
    pub health: String,
    pub certificate: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::certificate::Entity",
        from = "Column::Certificate",
        to = "super::certificate::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Certificate,
}

impl Related<super::certificate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Certificate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
